= Proposal compatibility Configuration Cache

== Introduction

The current Quarkus Gradle Plugin implementation does not support the Gradle Configuration Cache feature. This feature is important to improve the build time of the project, especially when the project has a large number of modules.
We observed different problems like:

* Project usage in the task actions
* Invalid configuration resolution

This proposal aims to implement the Gradle Configuration Cache feature in the Quarkus Gradle Plugin.
The scope of this proposal cover the tasks:

* `quarkusGenerateCode`
* `quarkusBuild`
* `quarkusBuildDependencies`
* `quarkusBuildCacheableAppParts`

=== Implementation
Instead of initializing the `ApplicationModel` during the task action, we provide a `QuarkusApplicationModelTask` that creates and serializes the `ApplicationModel` to a file.
Quarkus tasks compatible with Configuration cache define an input property representing the `ApplicationModel`, during the task action
the model is deserialized.
Additionally, this proposal updates the resolution logic with the compatible types required for configuration cache.

== Usage
We have published a snapshot compatible with Quarkus 3.10.1 version:

`build-logic/settings.gradle.kts`
```
maven { url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
```

`build-logic/build.gradle.kts`
```
implementation("io.github.cdsap:gradle-application-plugin:3.10.1-conf-cache-SNAPSHOT")
```
